services:
  db:
    image: mysql
    ports:
      - '8031:3306'
    env_file:
      - .env
    networks:
      - mynetwork
    restart: always
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8041:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - mynetwork
    restart: always
 
  backend:
    build: 
      context: ./backend
    container_name: expressjs_app
    restart: always
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8021:8021"

  frontend:
    build:
      context: ./frontend
    container_name: vue_app
    restart: always
    depends_on:
      - backend
    networks:
      - mynetwork
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8011:8011"

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
